project_id = "wjghdqkxwuyptxzdidtf"

[functions.router_llm]
verify_jwt = false

[functions.template_preview_llm]
verify_jwt = false

[functions.resolve_template]
verify_jwt = false

[functions.schema_manager]
verify_jwt = false

[functions.data_normalization]
verify_jwt = false

[functions.generate_email_draft]
verify_jwt = false