[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[auth.external.google]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[functions]
verify_jwt = true

[functions.post_to_n8n]
verify_jwt = false

[functions.post_to_n8n_2026]
verify_jwt = false

[functions.invite_user]
verify_jwt = true

[functions.list_users]
verify_jwt = true

[functions.delete_user]
verify_jwt = true

[functions.suggest_contact_groups]
verify_jwt = true

[functions.ai_tools]
verify_jwt = true

[functions.ai_add_opportunity_next_step]
verify_jwt = false

[functions.ai_create_or_update_opportunity]
verify_jwt = false

[functions.ai_add_contact_next_step]
verify_jwt = false

[functions.ai_create_or_update_contact]
verify_jwt = false

[functions.ai_add_contact_note]
verify_jwt = false

[functions.n8n_proxy]
verify_jwt = true
