-- Drop and recreate the view to add most_recent_group_contact column
DROP VIEW IF EXISTS contacts_with_dynamic_interactions;

CREATE VIEW contacts_with_dynamic_interactions AS
SELECT 
  id,
  full_name,
  first_name,
  last_name,
  email_address,
  title,
  organization,
  phone,
  url_to_online_bio,
  linkedin_url,
  x_twitter_url,
  category,
  contact_type,
  lg_sector,
  areas_of_specialization,
  lg_focus_areas_comprehensive_list,
  lg_focus_area_1,
  lg_focus_area_2,
  lg_focus_area_3,
  lg_focus_area_4,
  lg_focus_area_5,
  lg_focus_area_6,
  lg_focus_area_7,
  lg_focus_area_8,
  no_of_lg_focus_areas,
  lg_lead,
  lg_assistant,
  delta_type,
  delta,
  outreach_date,
  intentional_no_outreach,
  intentional_no_outreach_date,
  intentional_no_outreach_note,
  notes,
  group_contact,
  most_recent_group_contact,
  state,
  city,
  total_of_contacts,
  of_emails,
  of_meetings,
  days_since_last_email,
  days_since_last_meeting,
  email_subject,
  meeting_title,
  email_from,
  email_to,
  email_cc,
  meeting_from,
  meeting_to,
  meeting_cc,
  all_emails,
  no_of_opps_sourced,
  all_opps,
  created_at,
  updated_at,
  get_latest_contact_email(email_address) AS latest_contact_email,
  get_latest_contact_meeting(email_address) AS latest_contact_meeting,
  get_most_recent_contact_dynamic(email_address) AS most_recent_contact
FROM contacts_raw c;